#Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
name: Imaging Cloud Action Test
description : Lorem Ipsum is simply dummy
icon: activity
color: purple
on:
  push:
    branches: [ $default-branch ]
  workflow_dispatch:
jobs:
  run-imaging-cloud-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Pull docker image
        run: docker pull 
      - name: Run IL-CLI
        run: |
          echo ${{github.ref}} 
          cd ${{github.workspace}}
          docker run -e IMAGING_CLOUD_API_KEY=${{secrets.IMAGING_CLOUD_API_KEY}} -v $(pwd):/home/carl/extras/source castbuild/imaging-cloud-action:latest
